# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm-lockfile-prototype.spec

# add or remove files that should be synced
files_to_sync:
    - rpm-lockfile-prototype.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: rpm-lockfile-prototype
# downstream (Fedora) RPM package name
downstream_package_name: rpm-lockfile-prototype
